---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: chris530-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: 'https://github.com/chris530/examples.git'
      revision: main
      directories:
      - path: Apps/*
  template:
    metadata:
      name: '{{path[0]}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/chris530/examples.git
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
