---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: chris530-examples-appset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: 'https://github.com/chris530/examples.git'
      revision: main
      directories:
      - path: Apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/chris530/examples.git'
        path: '{{path}}'
        targetRevision: main
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: argocd
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
