apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: Apps
    repoURL: https://github.com/chris530/examples.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
